(() => {
'use strict';
const DONE_KEY='ruankao_daily_courses_done_v1';
const done=()=>{try{return new Set(JSON.parse(localStorage.getItem(DONE_KEY)||'[]'))}catch{return new Set()}};
const save=s=>{try{localStorage.setItem(DONE_KEY,JSON.stringify([...s]))}catch(_){}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dates=COURSES.map(x=>x.date);
function courseFileName(index){const title=COURSES[index].title.replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,'-');return `day-${String(index+1).padStart(2,'0')}-${title}.html`}
function courseUrl(date){const index=dates.indexOf(date);return index>=0?`课程/${courseFileName(index)}`:`当天课程.html?date=${date}`}
function lessonCourseUrl(date){const index=dates.indexOf(date);return index>=0?courseFileName(index):'#'}
function renderCatalog(){const root=document.getElementById('catalog');if(!root)return;const state=done();root.innerHTML=PHASES.map(p=>{const list=COURSES.filter(c=>c.phase===p.id);return `<section class="phase-block"><h2 class="phase-title">${p.title}</h2><div class="course-grid">${list.map((c)=>{const i=dates.indexOf(c.date)+1;return `<a class="course-card${state.has(c.date)?' done':''}" href="${courseUrl(c.date)}"><div class="course-date">DAY ${String(i).padStart(2,'0')}<small>${c.date.slice(5).replace('-','/')}</small></div><div><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p></div></a>`}).join('')}</div></section>`}).join('');document.getElementById('catalogProgress').textContent=`已完成 ${state.size} / ${COURSES.length}`;document.getElementById('continueCourse').onclick=()=>{const next=COURSES.find(c=>!state.has(c.date))||COURSES.at(-1);location.href=courseUrl(next.date)}}
function renderLesson(){const root=document.getElementById('lesson');if(!root)return;const date=window.LESSON_DATE||new URLSearchParams(location.search).get('date')||COURSES[0].date;const index=COURSES.findIndex(c=>c.date===date);const c=COURSES[index<0?0:index],t=TOPICS[c.topic]||TOPICS.review;document.title=`DAY ${index+1} · ${c.title}`;document.getElementById('dayCounter').textContent=`DAY ${String(index+1).padStart(2,'0')} / 65 · ${c.date}`;
root.innerHTML=`<header class="lesson-hero"><div class="lesson-label">${PHASES.find(p=>p.id===c.phase).title} · ${c.date}</div><h1>${esc(c.title)}</h1><p>${esc(c.summary)}</p><div class="time-plan">${c.time.split('｜').map(x=>`<span>${esc(x)}</span>`).join('')}</div></header>
<section class="lesson-section"><h2>今天学到什么程度</h2><div class="outcomes">${t.outcomes.map(x=>`<div class="outcome">${x}</div>`).join('')}</div></section>
<section class="lesson-section"><h2>小白讲解</h2>${t.concepts.map(x=>`<article class="concept"><h3>${x[0]}</h3>${x[1]}</article>`).join('')}<aside class="memory"><b>记忆主线</b><div>${t.memory}</div></aside></section>
<section class="lesson-section"><h2>跟着做一道例题</h2><article class="example"><h3>${t.example.title}</h3><p>${t.example.question}</p><ol class="steps">${t.example.steps.map(x=>`<li>${x}</li>`).join('')}</ol><p><strong>答案：</strong>${t.example.answer}</p></article>${t.tip?`<aside class="exam-tip"><strong>考试提醒：</strong>${t.tip}</aside>`:''}</section>
<section class="lesson-section"><h2>今天的练习题</h2><p>先独立作答，再点“查看答案”。错题要说清楚为什么错。</p>${t.quiz.map((q,i)=>`<article class="quiz-item"><h3>${i+1}. ${q.q}</h3>${q.options?`<div class="options">${q.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${o}</label>`).join('')}</div>`:''}<button class="answer-btn" type="button">查看答案与解析</button><div class="answer"><strong>答案：${q.a}</strong><br>${q.e}</div></article>`).join('')}</section>
<section class="lesson-section"><h2>5 分钟验收</h2><div class="checklist">${t.check.map(x=>`<label><input type="checkbox"> ${x}</label>`).join('')}<p><strong>通关标准：</strong>${t.pass}</p></div></section>`;
root.querySelectorAll('.answer-btn').forEach(b=>b.onclick=()=>{b.nextElementSibling.classList.toggle('open');b.textContent=b.nextElementSibling.classList.contains('open')?'收起解析':'查看答案与解析'});
const prev=document.getElementById('prevLesson'),next=document.getElementById('nextLesson'),standalone=/\/课程\/day-\d{2}-.+\.html$/i.test(decodeURIComponent(location.pathname));if(index>0)prev.href=standalone?lessonCourseUrl(COURSES[index-1].date):courseUrl(COURSES[index-1].date);else prev.classList.add('disabled');if(index<COURSES.length-1)next.href=standalone?lessonCourseUrl(COURSES[index+1].date):courseUrl(COURSES[index+1].date);else next.classList.add('disabled');const state=done(),finish=document.getElementById('finishLesson');function label(){finish.textContent=state.has(c.date)?'已完成 · 点击取消':'完成今天课程'}label();finish.onclick=()=>{state.has(c.date)?state.delete(c.date):state.add(c.date);save(state);label();finish.style.background=state.has(c.date)?'#2c6381':'#176b52'};if(state.has(c.date))finish.style.background='#2c6381'}
renderCatalog();renderLesson();
})();